### PR TITLE
Fix iOS 13 compatibility issue

### PR DESCRIPTION
**Pull request by iabdullin**
Attempt to fix https://github.com/openid/AppAuth-iOS/issues/400

### CODE REVIEW

**Comment by WilliamDenniss** [comment]
Thanks for the patch! Can you sign the [CLA ](https://openid.net/intellectual-property/contribution-license-agreement/) (or point me at your CLA if you did that already) so I can get this merged?

**Comment by iabdullin** [comment]
@WilliamDenniss , signed CLA, please check.

**Comment by WilliamDenniss** [comment]
Can you link me to your one when it posts? https://openid.net/intellectual-property/contribution-license-agreement/

**Comment by WilliamDenniss** [comment]
CLA received.

**Comment by WilliamDenniss** [comment]
LGTM, merging into the beta branch.

Am expecting further changes to this, but it's good for now. Thanks for your contribution!

**Pull request merged**
