### PR TITLE
Rename LICENSE to stonerdaniel jnc

### PR DESCRIPTION
**Pull request by Stonerdaniel**
national wwi museum

### CODE REVIEW

**Comment by Stonerdaniel** [comment]
ok

**Comment by mdmathias** [comment]
I don't think we want to rename this file.

**Review by Brooksie18 — COMMENTED** [review]
I do not remember giving approval to rename this!

**Review by Stonerdaniel — COMMENTED** [review]
[]()

**Comment by Stonerdaniel** [comment]
> I don't think we want to rename this file.

flag

**Pull request closed without merging**
