### PR TITLE
Improved Swift developer experience

### LINKED ISSUE #60: Conflicting nullability specifier warnings
There are couple of warnings when bridging the library with Swift 3 (Xcode 8)

```
AppAuth-iOS/Source/OIDAuthState.h:144:1: warning: conflicting nullability specifier on return types, 'nullable' conflicts with existing specifier 'nonnull'
- (nullable instancetype)init NS_UNAVAILABLE;
^
/Applications/Xcode.app/Contents/Developer/Platforms/iPhoneSimulator.platform/Developer/SDKs/iPhoneSimulator10.1.sdk/usr/include/objc/NSObject.h:60:1: note: previous declaration is here
- (instancetype)init
^

AppAuth-iOS/Source/OIDAuthorizationResponse.h:106:1: warning: conflicting nullability specifier on return types, 'nullable' conflicts with existing specifier 'nonnull'
- (nullable instancetype)init NS_UNAVAILABLE;
^
/Applications/Xcode.app/Contents/Developer/Platforms/iPhoneSimulator.platform/Developer/SDKs/iPhoneSimulator10.1.sdk/usr/include/objc/NSObject.h:60:1: note: previous declaration is here
- (instancetype)init
^

AppAuth-iOS/Source/OIDAuthorizationService.h:84:1: warning: conflicting nullability specifier on return types, 'nullable' conflicts with existing specifier 'nonnull'
- (nullable instancetype)init NS_UNAVAILABLE;
^
/Applications/Xcode.app/Contents/Developer/Platforms/iPhoneSimulator.platform/Developer/SDKs/iPhoneSimulator10.1.sdk/usr/include/objc/NSObject.h:60:1: note: previous declaration is here
- (instancetype)init
^

AppAuth-iOS/Source/OIDServiceDiscovery.h:358:1: warning: conflicting nullability specifier on return types, 'nullable' conflicts with existing specifier 'nonnull'
- (nullable instancetype)init NS_UNAVAILABLE;
^
/Applications/Xcode.app/Contents/Developer/Platforms/iPhoneSimulator.platform/Developer/SDKs/iPhoneSimulator10.1.sdk/usr/include/objc/NSObject.h:60:1: note: previous declaration is here
- (instancetype)init
^

AppAuth-iOS/Source/OIDTokenRequest.h:114:1: warning: conflicting nullability specifier on return types, 'nullable' conflicts with existing specifier 'nonnull'
- (nullable instancetype)init NS_UNAVAILABLE;
^
/Applications/Xcode.app/Contents/Developer/Platforms/iPhoneSimulator.platform/Developer/SDKs/iPhoneSimulator10.1.sdk/usr/include/objc/NSObject.h:60:1: note: previous declaration is here
- (instancetype)init
^

AppAuth-iOS/Source/OIDTokenResponse.h:97:1: warning: conflicting nullability specifier on return types, 'nullable' conflicts with existing specifier 'nonnull'
- (nullable instancetype)init NS_UNAVAILABLE;
^
/Applications/Xcode.app/Contents/Developer/Platforms/iPhoneSimulator.platform/Developer/SDKs/iPhoneSimulator10.1.sdk/usr/include/objc/NSObject.h:60:1: note: previous declaration is here
- (instancetype)init
^
```

Some other initializers also have questionable nullability specifiers, e.g.
OIDTokenRequest:
```
- (nullable instancetype)initWithConfiguration:(OIDServiceConfiguration *)configuration …
```

This initializer should be marked as nullable only when there are some circumstances where the initializer can return nil, which is not the case here. This initializer always returns value from NSObject’s init, which never returns nil:
https://developer.apple.com/reference/objectivec/nsobject/1418641-init

With the current annotations, many initializers are marked as “failable” in Swift, e.g.:
let tokenRequest = OIDTokenRequest(…)
initializes token request as optional and requires unnecessary unwrapping

### PR DESCRIPTION
**Pull request by WilliamDenniss**
– Added a test case to test that AppAuth compiles for Swift.
– `nullable` fixes to remove need for unnecessary unwrapping.

Fixes #60

---
This change is [Reviewable](https://reviewable.io/reviews/openid/appauth-ios/81)

### CODE REVIEW

**Comment by StevenEWright** [comment]
Reviewed 14 of 24 files at r1, 1 of 1 files at r3, 7 of 10 files at r4.
Review status: all files reviewed at latest revision, 5 unresolved discussions, some commit checks failed.

---

*[Source/OIDRegistrationRequest.h, line 94 at r4](https://reviewable.io:443/reviews/openid/appauth-ios/81#-KfMyl9B1wNLv729xXHw:-KfMyl9B1wNLv729xXHx:b-9y2tya) ([raw file](https://github.com/openid/appauth-ios/blob/e88ec0adb0033a00c18e56e7cf81e269760c3e25/Source/OIDRegistrationRequest.h#L94)):*
> ```objc
> - (instancetype)initWithConfiguration:(OIDServiceConfiguration *)configuration
>                redirectURIs:(NSArray<NSURL *> *)redirectURIs
>               responseTypes:(nullable NSArray<NSString *> *)responseTypes
> ```

Nit; longest parameter name only needs 4 spaces from left margin.

---

*[Source/OIDRegistrationRequest.m, line 67 at r4](https://reviewable.io:443/reviews/openid/appauth-ios/81#-KfMyYVcklNqYCn3-Tx4:-KfMyWw1zan3QltFPm2V:b-9y2tya) ([raw file](https://github.com/openid/appauth-ios/blob/e88ec0adb0033a00c18e56e7cf81e269760c3e25/Source/OIDRegistrationRequest.m#L67)):*
> ```objc
> - (instancetype)initWithConfiguration:(OIDServiceConfiguration *)configuration
>             redirectURIs:(NSArray<NSURL *> *)redirectURIs
>            responseTypes:(nullable NSArray<NSString *> *)responseTypes
> ```

Nit; longest parameter name only needs 4 spaces from left margin.

---

*[UnitTests/OIDAppAuthTests-Bridging-Header.h, line 20 at r4](https://reviewable.io:443/reviews/openid/appauth-ios/81#-KfMytAwjqB7-NBvIJQU:-KfMytAwjqB7-NBvIJQV:biw39os) ([raw file](https://github.com/openid/appauth-ios/blob/e88ec0adb0033a00c18e56e7cf81e269760c3e25/UnitTests/OIDAppAuthTests-Bridging-Header.h#L20)):*
> ```objc
> 
> //
> //  Use this file to import your target's public headers that you would like to expose to Swift.
> ```

Do we need this template comment?

---

*[UnitTests/OIDSwiftTests.swift, line 23 at r4](https://reviewable.io:443/reviews/openid/appauth-ios/81#-KfMz09w7cfrwhZ_lWz-:-KfMz09w7cfrwhZ_lWz0:bi4liyc) ([raw file](https://github.com/openid/appauth-ios/blob/e88ec0adb0033a00c18e56e7cf81e269760c3e25/UnitTests/OIDSwiftTests.swift#L23)):*
> ```Swift
> 
> /*! @brief Unit tests to verify Swift compatability.
>  */
> ```

I forget, is it this project's style to always have trailing */ on separate line, even for single-line javadoc comments?

---

*[UnitTests/OIDSwiftTests.swift, line 26 at r4](https://reviewable.io:443/reviews/openid/appauth-ios/81#-KfN0e_mFTS6YMovHkBi:-KfN0e_mFTS6YMovHkBj:b7yq4vr) ([raw file](https://github.com/openid/appauth-ios/blob/e88ec0adb0033a00c18e56e7cf81e269760c3e25/UnitTests/OIDSwiftTests.swift#L26)):*
> ```Swift
> class OIDSwiftTests: XCTestCase {
> 
>   /*! @brief Tests creation of a basic AppAuth object.
> ```

What are your plans for this test? I assume you don't want to duplicate tests already written in objective-c?

Is this just a smoke test that's checked into the project to act as a convenient Swift playground?

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/openid/appauth-ios/81)*

**Comment by WilliamDenniss** [comment]
Review status: 20 of 21 files reviewed at latest revision, 5 unresolved discussions.

---

*[Source/OIDRegistrationRequest.h, line 94 at r4](https://reviewable.io:443/reviews/openid/appauth-ios/81#-KfMyl9B1wNLv729xXHw:-KfN1VZ_VG4cqsSKy28U:b-q3dy9m) ([raw file](https://github.com/openid/appauth-ios/blob/e88ec0adb0033a00c18e56e7cf81e269760c3e25/Source/OIDRegistrationRequest.h#L94)):*
<details><summary><i>Previously, StevenEWright (Steven E Wright) wrote…</i></summary><blockquote>

Nit; longest parameter name only needs 4 spaces from left margin.
</blockquote></details>

I do count 4. 
`    tokenEndpointAuthMethod:(nullable NSString *)tokenEndpointAuthMethod`

---

*[Source/OIDRegistrationRequest.m, line 67 at r4](https://reviewable.io:443/reviews/openid/appauth-ios/81#-KfMyYVcklNqYCn3-Tx4:-KfN1t4f6OMFmTT9jcFY:b-hpazwj) ([raw file](https://github.com/openid/appauth-ios/blob/e88ec0adb0033a00c18e56e7cf81e269760c3e25/Source/OIDRegistrationRequest.m#L67)):*
<details><summary><i>Previously, StevenEWright (Steven E Wright) wrote…</i></summary><blockquote>

Nit; longest parameter name only needs 4 spaces from left margin.
</blockquote></details>

`    tokenEndpointAuthMethod:(nullable NSString *)tokenEndpointAuthMethod`

---

*[UnitTests/OIDAppAuthTests-Bridging-Header.h, line 20 at r4](https://reviewable.io:443/reviews/openid/appauth-ios/81#-KfMytAwjqB7-NBvIJQU:-KfN68ZHUKLwVjVPkomd:b1z7qls) ([raw file](https://github.com/openid/appauth-ios/blob/e88ec0adb0033a00c18e56e7cf81e269760c3e25/UnitTests/OIDAppAuthTests-Bridging-Header.h#L20)):*
<details><summary><i>Previously, StevenEWright (Steven E Wright) wrote…</i></summary><blockquote>

Do we need this template comment?
</blockquote></details>

Re-worded.

---

*[UnitTests/OIDSwiftTests.swift, line 23 at r4](https://reviewable.io:443/reviews/openid/appauth-ios/81#-KfMz09w7cfrwhZ_lWz-:-KfN6FSRz3RX5mW4Dp_A:bc309sw) ([raw file](https://github.com/openid/appauth-ios/blob/e88ec0adb0033a00c18e56e7cf81e269760c3e25/UnitTests/OIDSwiftTests.swift#L23)):*
<details><summary><i>Previously, StevenEWright (Steven E Wright) wrote…</i></summary><blockquote>

I forget, is it this project's style to always have trailing */ on separate line, even for single-line javadoc comments?
</blockquote></details>

It appears so.

---

*[UnitTests/OIDSwiftTests.swift, line 26 at r4](https://reviewable.io:443/reviews/openid/appauth-ios/81#-KfN0e_mFTS6YMovHkBi:-KfN6HUVtfZbnJ4n3WHU:b2r3k1l) ([raw file](https://github.com/openid/appauth-ios/blob/e88ec0adb0033a00c18e56e7cf81e269760c3e25/UnitTests/OIDSwiftTests.swift#L26)):*
<details><summary><i>Previously, StevenEWright (Steven E Wright) wrote…</i></summary><blockquote>

What are your plans for this test? I assume you don't want to duplicate tests already written in objective-c?

Is this just a smoke test that's checked into the project to act as a convenient Swift playground?
</blockquote></details>

It's a smoke test to verify that AppAuth builds for Swift environments.

In the future, I hope to see more Swift-specific tests. I don't see a huge need for duplication, my hope would be for tests relevant to Swift.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/openid/appauth-ios/81)*

**Comment by StevenEWright** [comment]
Reviewed 1 of 1 files at r5.
Review status: all files reviewed at latest revision, 2 unresolved discussions, some commit checks failed.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/openid/appauth-ios/81)*

**Comment by StevenEWright** [comment]
:lgtm:

---

Review status: all files reviewed at latest revision, 2 unresolved discussions, some commit checks failed.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/openid/appauth-ios/81#-:-KfNLmetQ2xGPjKxHOpF:bnfp4nl)*

**Comment by StevenEWright** [comment]
Review status: all files reviewed at latest revision, 1 unresolved discussion, some commit checks failed.

---

*[UnitTests/OIDSwiftTests.swift, line 29 at r5](https://reviewable.io:443/reviews/openid/appauth-ios/81#-KfNUUQi8ENSoz4GGemJ:-KfNUUQi8ENSoz4GGemK:bl8ttue) ([raw file](https://github.com/openid/appauth-ios/blob/d71867db76e213831ddb1e5f536f73f7deac8c91/UnitTests/OIDSwiftTests.swift#L29)):*
> ```Swift
>    */
>   func testSwift() {
>     let authorizationEndpoint = URL(string: "https://example.com/authorization")!
> ```

I realize this is just a smoke test... but because we haven't worked on Swift together, and I'd like to understand the conventions we plan to have our swift code adopt, should this be:


  guard let authorizationEndpoint = URL(string: "https://example.com/authorization") else {
    XCTAssert(NO, "The authorization endpoint URL could not be created.")
  }

?

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/openid/appauth-ios/81)*

**Comment by WilliamDenniss** [comment]
Review status: all files reviewed at latest revision, 1 unresolved discussion, some commit checks failed.

---

*[UnitTests/OIDSwiftTests.swift, line 29 at r5](https://reviewable.io:443/reviews/openid/appauth-ios/81#-KfNUUQi8ENSoz4GGemJ:-KfOJQWRozpu-Gdq0FDO:b-kqq7gq) ([raw file](https://github.com/openid/appauth-ios/blob/d71867db76e213831ddb1e5f536f73f7deac8c91/UnitTests/OIDSwiftTests.swift#L29)):*
<details><summary><i>Previously, StevenEWright (Steven E Wright) wrote…</i></summary><blockquote>

I realize this is just a smoke test... but because we haven't worked on Swift together, and I'd like to understand the conventions we plan to have our swift code adopt, should this be:


  guard let authorizationEndpoint = URL(string: "https://example.com/authorization") else {
    XCTAssert(NO, "The authorization endpoint URL could not be created.")
  }

?
</blockquote></details>

For nullable methods, generally yes. However I argue that in this case we know it won't ever (practically) be null, and if it was null I wouldn't mind if it crashed.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/openid/appauth-ios/81)*

**Pull request merged**
