### PR TITLE
Remove platforms declaration to avoid deployment target warnings

### PR DESCRIPTION
**Pull request by CemYil03**
This is required to fix the following warning in Xcode 13.1:
"The iOS Simulator deployment target 'IPHONEOS_DEPLOYMENT_TARGET' is set to 8.0, but the range of supported deployment target versions is 9.0 to 15.0.99."

### CODE REVIEW

**Comment by Oliver-Binns** [comment]
@CemYil03 since the deployment target specified is actually the base required for Swift Package Manager, I'd suggest removing the platforms declaration entirely. This will remove the build warning that appears in lower versions of Xcode too.

I recommend taking a look at these two links if you want further information:
https://forums.swift.org/t/xcode12-minimum-deployment-target-and-spm/40467
https://github.com/nanopb/nanopb/pull/585/files

**Review by khalideali — APPROVED** [review]

**Comment by simonseyer** [comment]
I would second @Oliver-Binns comment. Would be great if you could apply the change by removing the `platforms` definition altogether.

**Comment by CemYil03** [comment]
First I thought this could result in compile errors, but it seems to work. The change is now in the latest commit

**Review by Oliver-Binns — APPROVED** [review]

**Comment by CemYil03** [comment]
Would really like to merge it in asap

**Comment by Oliver-Binns** [comment]
@WilliamDenniss looks like you've merged a few recently? 🙂 please can you take a look here?

**Review by crazyguero — APPROVED** [review]

**Comment by CemYil03** [comment]
Someone like @WilliamDenniss or @julienbodet do you have the rights to perform a merge?

**Comment by khalideali** [comment]
@petea Can you take a look at this?

**Comment by khalideali** [comment]
@marcoceppi @iainmcgin @panva Sorry to bother you, but can anyone from openid review and merge this pull request?

**Comment by marcoceppi** [comment]
I unfortunately can only review the PHP OpenID project. Asking here may help: http://lists.openid.net/mailman/listinfo/openid-code

**Review by AnarionII — APPROVED** [review]

**Comment by marcoceppi** [comment]
@petea Is this something you can help review and merge?

**Comment by petea** [comment]
This has been addressed with #690

**Comment by nh7a** [comment]
@petea did you see [Oliver-Binns](https://github.com/Oliver-Binns)'s https://github.com/openid/AppAuth-iOS/pull/661#issuecomment-977207559? Surely, #690 is better than nothing, but it'll only work until it'll break soon.

**Comment by petea** [comment]
@nh7a I did, and will consider taking that step next.

**Pull request closed without merging**
