### PR TITLE
Remove IPHONEOS_DEPLOYMENT_TARGET warning by upgrading iOS to 9

### PR DESCRIPTION
**Pull request by minuscorp**

### CODE REVIEW

**Comment by CemYil03** [comment]
#661 already covers this.

**Comment by minuscorp** [comment]
Still not merged though

**Comment by Oliver-Binns** [comment]
#661 is a better implementation of this. It would be preferable to merge that instead.

The platform declarations can be removed entirely as they match the minimum version supported by SPM:
https://forums.swift.org/t/xcode12-minimum-deployment-target-and-spm/40467
https://github.com/nanopb/nanopb/pull/585/files

**Comment by minuscorp** [comment]
I saw it, and saw that it wasn't reviewed that's why I posted another one. I really hate warnings in projects.

**Comment by mattneub** [comment]
Please merge this change! We need to get this warning off our plate.

**Comment by petea** [comment]
This was addressed in #690 and released with 1.5.0.  What warning are you seeing?

**Comment by mattneub** [comment]
Yes, I just realized that. The problem is that AppAuth is an indirect dependency so I'm not certain that the version we get is up to us. We're looking into it! Thanks.

**Pull request closed without merging**
