### PR TITLE
Fixed an end session callback

### PR DESCRIPTION
**Pull request by AndrewMcDrew**
Addressed an issue pointed out in [WIP](https://github.com/openid/AppAuth-iOS/pull/259#issuecomment-409830558) by @Amnell

### CODE REVIEW

**Comment by WilliamDenniss** [comment]
Thanks for the contribution. Can you sign the [CLA](https://openid.net/intellectual-property/contribution-license-agreement/), or point me at your CLA if you did this already?

**Comment by AndrewMcDrew** [comment]
Done already https://www.docusign.net/Signing/?ti=24e76679dc714b50b4154f45210c73b8

**Comment by AndrewMcDrew** [comment]
Yea, now I see. Haven’t sent the document to the help@oidf.org. Now also done, sorry for that.

**Comment by AndrewMcDrew** [comment]
Now posted on the official site http://openid.net/wordpress-content/uploads/2018/09/Andrew-Urban_CLA-Agreement-Individual_2018-09-12.pdf

**Comment by WilliamDenniss** [comment]
@mattio tested this: https://github.com/openid/AppAuth-iOS/pull/259#issuecomment-431026792

Looks good conceptually, LGTM.

**Pull request merged**
