### PR TITLE
Add modal presentation options for SFSafariVC

### PR DESCRIPTION
**Pull request by maxsz**
Adds support for specifing the modal presentation and transition styles of the presented SFSafariViewController.

---

This change is [Reviewable](https://reviewable.io/reviews/openid/appauth-ios/28)

### CODE REVIEW

**Comment by WilliamDenniss** [comment]
I believe this is a feature we want. May need to rebase on pull request #30 once that's done.

Should we add [preferredBarTintColor](https://developer.apple.com/reference/safariservices/sfsafariviewcontrollerconfiguration/1648469-preferredbartintcolor?language=objc) and [tintColor](https://developer.apple.com/reference/uikit/uiview/1622467-tintcolor?language=objc) options too?

Can you [sign the CLA](https://github.com/openid/AppAuth-iOS/blob/master/CONTRIBUTING.md)?

**Comment by maxsz** [comment]
Great 👍. 

As there might be more options and other things we might want to configure on the view controller, I think there are two possible solutions. 

1. Create a "style" class/struct that has all the properties and pass it in (this is better than having more and more parameters to the already very long methods like `authStateByPresentingAuthorizationRequest :presentingViewController:modalPresentationStyle:modalTransitionStyle:callback:`)

2. Pass a closure to the methods which returns the configured SFSafariViewController. This is the most flexible option, as we won't need to adapt/change the API for new iOS versions when new properties become available (like the `preferredBarTintColor ` of `SFSafariViewControllerConfiguration` you mentioned, which will be added in iOS 10). I'm thinking something like this:
```objective-c
 - (void)presentSafariViewControllerWithViewController:(UIViewController *)parentViewController
                                       configuration:(SFSafariViewController (^)(void))configurationBlock
                                              callback:(OIDAuthorizationCallback)authorizationFlowCallback {
    _pendingauthorizationFlowCallback = authorizationFlowCallback;
    NSURL *URL = [_request authorizationRequestURL];
    if ([SFSafariViewController class]) {
      SFSafariViewController *safariVC;
      if (configurationBlock) {
        safariVC = configurationBlock();
      }
      if (!safariVC) {
       safariVC = [[SFSafariViewController alloc] initWithURL:URL
                                                       entersReaderIfAvailable:NO];
      }
      safariVC.delegate = self;
      _safariVC = safariVC;
      [parentViewController presentViewController:safariVC animated:YES completion:nil];
    }
   ...
}
```

What would you guys prefer? Do you have other options in mind?

Regarding the CLA: I'm acting on behalf of equinux AG and we've already signed the CLA (https://github.com/openid/AppAuth-iOS/issues/20#issuecomment-229709325).

**Comment by StevenEWright** [comment]
I have proposed an alternative here: [https://github.com/openid/AppAuth-iOS/pull/34](https://github.com/openid/AppAuth-iOS/pull/34)

**Comment by WilliamDenniss** [comment]
Firstly, thank you @maxsz for starting this discussion, it's definitely a feature that's lacking in AppAuth and I appreciate your ideas and code! 

So we have three alternatives suggested so far:
1. Add a param in the constructor for everything (this PR, #28).
2. Add a configuration block.
3. Add a factory (#34).

I'm inclined to agree with your assessment regarding point 1), that we'll end up with really long methods. At a minimum we'd want tintColor, and the list could grow quite long, and it seems like the less favored option.

Regarding 2) I think that's a nice solution for one-offs (less code than creating a class per 3)), but I also think it feels less reusable. Let's say AppAuth offers 2 styles, Apple's default (blue tint, etc), and the AppAuth opinionated style (e.g. with a 55%-gray 'Done' button), or an extension like GTMAppAuth wants to offer a Google flavored default config. Offering these default styles in the API as a factory implementation seems nicer to me than offering them as a block.  I expect 99% of developers will use one of the provided styles, making the "convenience" advantage of the block option a moot point.

So I'm casting my vote for 3). I'm guessing Steve is too since he proposed it. What do you think?

I realise this has been open a long time! Let's look at resolving it ASAP now.

**Comment by maxsz** [comment]
Thanks @WilliamDenniss for coming back to this. I'm also happy with option 3) and PR #34. So I'm closing this.

**Pull request closed without merging**
