### PR TITLE
Add iOS framework target

### PR DESCRIPTION
**Pull request by hzalaz**
iOS framework target that allows lib to be included using Carthage.

---

This change is [Reviewable](https://reviewable.io/reviews/openid/appauth-ios/36)

### CODE REVIEW

**Comment by hzalaz** [comment]
This closes #25. Also not sure if you guys need an example in the repo

**Comment by clayellis** [comment]
@hzalaz @WilliamDenniss Any updates on the review above? Carthage support is a must for growth in the iOS community.

**Comment by StevenEWright** [comment]
Reviewed 1 of 6 files at r1.
Review status: 1 of 6 files reviewed at latest revision, 1 unresolved discussion, some commit checks failed.

---

*[Source/Framework/AppAuth.h, line 1 at r1](https://reviewable.io:443/reviews/openid/appauth-ios/36#-KYKHU4AE6Xy1f9aN2Lr:-KYKHU4BEgf_HOFtpoY2:b-sw5cka) ([raw file](https://github.com/openid/appauth-ios/blob/89ac295586e3587770bb030f860c95a4d1778f0d/Source/Framework/AppAuth.h#L1)):*
> ```objc
> /*! @file AppAuth.h
> ```

I feel we should be using the same umbrella header that already exists, otherwise we will have to keep multiple umbrella headers in sync?

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/openid/appauth-ios/36)*

**Comment by hzalaz** [comment]
Review status: 1 of 6 files reviewed at latest revision, 1 unresolved discussion, some commit checks failed.

---

*[Source/Framework/AppAuth.h, line 1 at r1](https://reviewable.io:443/reviews/openid/appauth-ios/36#-KYKHU4AE6Xy1f9aN2Lr:-KYKIZmm6HjtkIxu-Bwy:b5ihg0i) ([raw file](https://github.com/openid/appauth-ios/blob/89ac295586e3587770bb030f860c95a4d1778f0d/Source/Framework/AppAuth.h#L1)):*
<details><summary><i>Previously, StevenEWright (Steven E Wright) wrote…</i></summary><blockquote>

I feel we should be using the same umbrella header that already exists, otherwise we will have to keep multiple umbrella headers in sync?
</blockquote></details>

Yes, it's not ideal but I think the framework umbrella header should use the `<>` import style but will check it during the weekend to see if I can get around this.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/openid/appauth-ios/36)*

**Comment by StevenEWright** [comment]
Review status: 1 of 6 files reviewed at latest revision, 1 unresolved discussion, some commit checks failed.

---

*[Source/Framework/AppAuth.h, line 1 at r1](https://reviewable.io:443/reviews/openid/appauth-ios/36#-KYKHU4AE6Xy1f9aN2Lr:-KYKOFyA2RH4w6tSsJ46:b-rljsno) ([raw file](https://github.com/openid/appauth-ios/blob/89ac295586e3587770bb030f860c95a4d1778f0d/Source/Framework/AppAuth.h#L1)):*
<details><summary><i>Previously, hzalaz (Hernan Zalazar) wrote…</i></summary><blockquote>

Yes, it's not ideal but I think the framework umbrella header should use the `<>` import style but will check it during the weekend to see if I can get around this.
</blockquote></details>

Ah, yes, I see, and you are right. I didn't realize the existing umbrella header wasn't referencing the files that way. Let me chat with William and see what's up. Do you have a suggestion in the meantime?

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/openid/appauth-ios/36)*

**Comment by StevenEWright** [comment]
@WilliamDenniss PTAL

**Comment by sunenielsen** [comment]
Did this request die, or are someone still working on it? Not having Carthage support is really annoying when we were finally about to replace cocoa pods with something a lot better.

**Comment by WilliamDenniss** [comment]
I'd love to see Carthage support.

This PR needs to be updated with new classes that were added, and I'd like to see an example project in `Examples/` that uses Carthage, that we can use for testing (including CI) & documentation.

If someone can do that work to refresh the PR, I'll make sure this gets reviewed ASAP.

**Comment by hzalaz** [comment]
@WilliamDenniss will take care of that

**Comment by hzalaz** [comment]
@WilliamDenniss updated the PR with latest master changes and also added targets for tvOS & macOS fwk besides iOS.

Also added a new example project using Carthage, it's configured to pull the dependency from this repo for when its  merged but if you need to test you need to change the [Cartfile](https://github.com/hzalaz/AppAuth-iOS/blob/master/Examples/Example-iOS_ObjC-Carthage/Cartfile#L1) to use my fork `github "hzalaz/AppAuth-iOS" "master"`.

Is there any way I can see why the build failed?

**Comment by WilliamDenniss** [comment]
Thanks for all the work @hzalaz!

There were massive merge conflicts with the XCodeProj, so I ended up creating the Framework targets again from scratch. I also added test targets for each framework. Updated PR #97 adds the framework, and cherry-picks your example & documentation commits.

**Pull request closed without merging**
