### PR TITLE
Added withFreshTokensPerformActionWithAdditionalParameters to OIDAuthState

### PR DESCRIPTION
**Pull request by ProjectLane**
This PR adds a way to include additional parameters when a token needs to be refreshed.  This way previously only achievable by constructing the request, performing the refresh, and updating the auth state manually.

---

This change is [Reviewable](https://reviewable.io/reviews/openid/appauth-ios/49)

### CODE REVIEW

**Comment by WilliamDenniss** [comment]
Thanks for the pull request @ProjectLane.

Can you eSign the CLA & [contributor agreement](https://github.com/openid/AppAuth-iOS/blob/master/CONTRIBUTING.md) so we can merge it in?

**Comment by ProjectLane** [comment]
@WilliamDenniss Sorry for the delay.  I just signed the documents, but let me know if anything was missed.  Thank you!

**Comment by WilliamDenniss** [comment]
Reviewed 2 of 2 files at r1.
Review status: all files reviewed at latest revision, 2 unresolved discussions, some commit checks failed.

---

*[Source/OIDAuthState.h, line 216 at r1](https://reviewable.io:443/reviews/openid/appauth-ios/49#-KVpqjdTEinftdlFf42x:-KVpqjdTEinftdlFf42y:b-td00ro) ([raw file](https://github.com/openid/appauth-ios/blob/e8dacb155a6b06650354b239473c316c694e12cb/Source/OIDAuthState.h#L216)):*
> ```objc
>         thread.
>  */
> - (void)withFreshTokensPerformActionWithAdditionalParameters:
> ```

Can you name this:

`performActionWithFreshTokens:(OIDAuthStateAction)action additionalRefreshParameters:(nullable NSDictionary<NSString *, NSString *> *)additionalParameters`

Two reasons:
1) I think it's best to say additional*Refresh*Param to be clear the params relate to the refresh, and
2) I plan to rename `withFreshTokensPerformAction` to `performActionWithFreshTokens` based on some other feedback – may as well not add a new method with the old naming style.

---

*[Source/OIDAuthState.m, line 444 at r1](https://reviewable.io:443/reviews/openid/appauth-ios/49#-KVpsFyw2e24TLjzOKVL:-KVpsFyxvXYKQ77gk3rD:bs6fhg0) ([raw file](https://github.com/openid/appauth-ios/blob/e8dacb155a6b06650354b239473c316c694e12cb/Source/OIDAuthState.m#L444)):*
> ```objc
>     // refresh the tokens
>     OIDTokenRequest *tokenRefreshRequest =
>       [self tokenRefreshRequestWithAdditionalParameters:additionalParameters];
> ```

This should be indented by 4 space characters not 2, since it's a line wrap.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/openid/appauth-ios/49)*

**Comment by WilliamDenniss** [comment]
Thanks for signing the CLA! I've reviewed your PR, see comments.

**Comment by WilliamDenniss** [comment]
Merged as part of #55.

**Pull request closed without merging**
