### PR TITLE
Update parameter nullability

### LINKED ISSUE #565: OIDEndSessionRequest initializers lack correct nullability specifiers
**Are you filing an issue about iOS 12?**
No

**Describe the bug**
`OIDEndSessionRequest.h` brackets its declarations with `NS_ASSUME_NONNULL`, which means that all object-typed parameters will be bridged into Swift as non-optional, unless otherwise specified.

The initializers to create an `OIDEndSessionRequest` allow you to pass in an `idTokenHint:(NSString *)idTokenHint` parameter, which lacks the `nullable` specifier. This means that in Swift, that parameter is bridged as `String`, and not `String?`.

The `@property` for this parameter correctly shows it as `nullable`, and the implementation allows for the underlying ivar to be `nil`, which means the initializer parameter should allow `nil` values as well.

The same applies to the `postLogoutRedirectURL:(NSURL *)postLogoutRedirectURL` and `state:(NSString *)state` parameters.

**Expected behavior**
These initializer parameters are declared as `(nullable NS... *):`

### PR DESCRIPTION
**Pull request by davedelong**
Fixes #565

### CODE REVIEW

**Comment by Tizzit-max** [comment]
Thank you

**Comment by dermaaarkus** [comment]
Would be great to see this merged!

**Comment by philet** [comment]
> @davedelong could you update the nullability annotations for the initializer implementations as well?

@davedelong If you give me access to the branch for this pull request I could do this update. (I'd be glad to get this pull request merged too.)

**Comment by davedelong** [comment]
@petea @philet I'm not using this project anymore and am intending to delete my fork just to keep my personal GitHub tidy. You're welcome to copy the diff and re-apply it. All I did was add 5 nullability annotations.

**Comment by philet** [comment]
@davedelong @petea Ok. I created a new pull request for this issue: https://github.com/openid/AppAuth-iOS/pull/702

**Pull request closed without merging**
