### PR TITLE
Adds defines module to AppAuth.podspec

### LINKED ISSUE #844: AppAuth cannot be integrated as static libraries with CocoaPods because it does not define a module (`DEFINES_MODULE`)
**Describe the bug**
AppAuth cannot be added as a transitive dependency of a CocoaPods pod, when built as a static library.

**To Reproduce**
1. [Install CocoaPods.](https://guides.cocoapods.org/using/getting-started.html#installation)
2.  In Xcode, make new iOS app project. 
2. cd into the directory and `pod init` to initialize CocoaPods.
3. In the generated `Podfile` comment out `use_frameworks!` to embed as static libs.  Add a pod that depends on `AppAuth`, for example, `GTMAppAuth`:
```ruby
  # Comment the next line if you don't want to use dynamic frameworks
  # use_frameworks!
  pod 'GTMAppAuth', '4.1.1'
```
5. Run `pod install`, which fails:
```
$ pod install
Analyzing dependencies
Downloading dependencies
Installing AppAuth (1.7.3)
Installing GTMAppAuth (4.1.1)
Installing GTMSessionFetcher (3.3.2)
[!] The following Swift pods cannot yet be integrated as static libraries:

The Swift pod `GTMAppAuth` depends upon `GTMSessionFetcher` and `AppAuth`, which do not define modules. To opt into those targets generating module maps (which is necessary to import them from Swift when building as static libraries), you may set `use_modular_headers!` globally in your Podfile, or specify `:modular_headers => true` for particular dependencies.
```

**Expected behavior**
`pod install` should succeed when adding a pod with a dependency on `AppAuth`.

**Environment**
macOS 14.4.1
CocoaPods 1.14.3

**Additional context**
`AppAuth` is not setting up a module, and doesn't have `DEFINES_MODULE` for that to be done automatically.

This can be fixed by adding `DEFINES_MODULE` to [AppAuth.podspec](https://github.com/openid/AppAuth-iOS/blob/master/AppAuth.podspec).  See [CocoaPods documentation about modular headers](https://blog.cocoapods.org/CocoaPods-1.5.0/#modular-headers).
```ruby
  s.xcconfig = {
     'DEFINES_MODULE' => 'YES',
  }
```

### PR DESCRIPTION
**Pull request by mdmathias**
Fixes #844

### CODE REVIEW

**Review by yalkhder — APPROVED** [review]

**Comment by mdmathias** [comment]
Waiting to merge based on result of [Firebase/SpecStaging](https://github.com/google/gtm-session-fetcher/pull/385#issuecomment-2030320345).

**Comment by mdmathias** [comment]
Merging since Firebase nightly tests look good with a [similar gtm-session-fetcher change](https://github.com/google/gtm-session-fetcher/pull/385#issuecomment-2032455559).

**Comment by vonovak** [comment]
Hello and thanks for this fix 🙂

Would it be possible to have this released (and also the change in gtm) soon?

There are downstream packages building on top of this, such as RN Google sign in and maybe Flutter and others that are hitting #844 and having this published would make it easy to use the latest versions.
Thank you 🙂

**Comment by mdmathias** [comment]
@vonovak yes, the plan is to release this soon. I don't have a specific date to share because of privacy manifest work that I am responsible for elsewhere. I hope to get to this release in a week or two. Apologies for the delay.

I believe downstream clients can fix their issue -- by using `use_frameworks!` in their `Podfile` for example. I do think adding `DEFINES_MODULE` here is important since it means downstream clients do not need to make a fix on their own.

**Pull request merged**
